travis:
  secure:
    BINSTAR_TOKEN: K6IWlK2f+DAl3x/p9mp+7fhZPrJjtse6xZUhtCBAIdFtLh+wKfGsDIqU0mb+RB7V1bOOdBU8qvuBFNLHqNItAqkOVIpsYHRG1/IwyZjOW8zgO/bLbEem5C6k+f/46fHLaLvkC/rB6HTN2gEG7Pw7G69ysDoQcwvdmGLOWxOlKxL7NaQHDDS7jlEFzTSztSlXwrs4xCUK6kpcbdRqYbZpTlLMbjq2DoGHIf79Mf//gGpiCajgdkHGMyFyivteEI733HQvfWaDHEfzDS2WFciCvgpCV15jdM2lBGuVa0t1+p1R8mwM/a5KIkLRgudCjXte1IbYeCsRY7RLcg0faWkVpIcd+dFycJHG3MeGolnSDS8NesC4ZZy4bc2XwDjQZgo2Q65CLNeoDLDc/nmHc90+mJ9XNc4ALjrV6f1FOZHC/l/qX/ShOTcJqbusJ5m4Hft3ZQSLd8jlAMoyppPTY2qzQAg+J/2OotxnFhHWB22q8o9JxAiD28wdh/v3LWoQM/MxMgpMpj78qleTMJg/UUWbwUImUqURiAQEoPsm9LMYJv8x9FpEcxX4u2pkKAvA72Hcn9sZFqwuvcCljyVdkSlg32jtP75kUg6d0HQ/COQ8rGgHoATsFJtEtBJ1ShAoBb12SkLX+cCe1GHnKKcugiqY2vWak9uyDYr9iSC3iqDPLVw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
