travis:
  secure:
    BINSTAR_TOKEN: XKJTPO0UrHArg94L5wN1+YXw02iZ2TYkQCcjvdHyrduUI5qCaekOMDnkNviz4tHyUoq629P9rUhjyVQ/rPL8Bdi5ZSVnLD+HCjVoXgkZc3MyT36EjFVQFihfV8HxrY+3rAOUyVWvrBBv9PiA5F/lUgHI2O4vtG7Ngqo8h37Yn+nFsYHgQn9+wJOAy8EjbtIXjymrGNx9R/Fj6Z+P9ggxkbB21z221k2/7F5MCQvouguAt29B17Cwiba1/w4pMOjavUu0grVgqur2Ee31SGtNHp1d1NL3NMKBnjSAJiAMbmpjeZyYFd7fvzTxQmtOmUYUvANRFpkiF9u41GUlymbuYC4V8Eis1vB9zh8GSnG7msyIIg2HN+GjbsbX1ELLnKp1/Jbe3MUf9HAGnJ59O8V81UTqFKFeUkn/6mSZnHZReWsdQWNMAbLAIUS3bJ2TWngUg9to1nbwSu+3KfUBoK4onC1mpvcVhcz33Z+F4ab7lgSykOabUXMtoll9Cj5kyzNbsry+Q5o41jTJcFABaCsuXBgozWef+UxV9HhCawhOHiI8RNQj8O/lpYqMjVw1dRG4hb3J9S8ZA3AW6eTbYtdME8E/MznZ797Bo0JcEg6kw0myoALI4AbpnWgJFiiOZZdQIEe+LsixfSOX2wY/NkBBj++HhKRvYm8y976XDTrbeP8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
