travis:
  secure:
    BINSTAR_TOKEN: QPNPCefPqkQFJ4VyHfT7ccmRdtDoM7M9JHIrCXm2LJMMpKwWzdWQT2dWMNdfWqTjg/Z3F+12rjHJHCEMkA7uT71T6X5bXuOIfgcC1ZqF2Di+nXnlS2QlfIhHpnGblRcnE0wENty1iwq4O+Cu3AqxnELlANqSZfz+EL2id33bZ8tIJvej8bQUyqdj4Oc+Clb1pmzy2Xwf8VaBhO3k03OS+B0EPy6iDyR2QheHaqbMKyeViG/hebxwQG7xo+vRk/QIgAhNeec4wbYrhc6zYQT+jV3in+wvN05AgiVsXr7H5+IP+JMScyDIU4aThemMQk3MonqyumvFG17vhMntv65OhaU8mvLcy6KlJh6gPqPZKi4uTV7BnvFuaS2IaDNlJ/Qw/EF7ursXM/7vgoBFKlh80xGvZF5zuE/vcv43zKOawQcDie1OKt79wT265fK27BVghJ4KXze6ax2tShytTXnugXjpUVh+QlyHO1uJ4wH2SHKI+ihxUxBhTi3n1L/sFvSyZ2YY6nuwDYMWXYzHV3tNrRqbyRuuhFCnBVNomSDCbBU+yuIouvikpQ4IvIjIE5vKl/74d+hV/d8UrGfmHbIjTA/HWhW2ZhTvYzkfFJtrxPTVWoI51pZGuZZnSyk1xu6ld/7licl89tMyztJXjY8aJQwX8RvA3CMYHk68kh9m3j0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
