travis:
  secure:
    BINSTAR_TOKEN: S+WmuMANJRQbWxwHn9nx3REBt74j/d3PMl4aOeO40QD5LHrAHTNwB3auQKeWpogaWCi0c0H4L4T1L8/q525+qoUBQIwKOZu9TFQIeXADTJvgI9+eA/076wgMAry7+vu7C1sP0/5WWILJvhV7z/0DWyh9eDJ/P5zAMmLefNjVP0xlpO59YUxEJbcIOcHEUS0MT07MvOMAsRdnaTcwRE2mQpkf9uTMmS8kFV2Ewdx2wI8KH2CJoWk4bAka3dukoTW6j74L18CJdEu6Khic+sFEpdrBRJtWWa9uG/+tP/wQORS1xeQFLrYxI2TYx6HJN22PYdGJoam5ZDVm3BrQ2L2ylStcXePO4J765zpoVbK6PcpUPvHAFh7HfPkH7YIDHPb2QQMcT7CkKkezOEEv1HZ76bQWVG6RVN8nc2r3ERrzRsptfytQoWe+eTeT7kXMWzIE/JT2p3ekO6RJyG0zjyARVNosgoKVIR7Dc+r8yeKUNaLTTD0o7wtnniexCvteHK12ZPVDqhn9KBcAAvRYfb5blD2CRKYJLyIA0Mx/ZGxfahEu8RiPOrqt8q3RHKMwpcdjbCclDvXgqikyiIt3UkLzs6qxG9WDToZVJzUQSHmx5hMAmZ1/GhaqA+G8JtH3tTXkg3szvba20kgr88UrGsf8U2cgh4muALPdYKYZftKXZsE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
